### ISSUE TITLE
Token Value not work

### ISSUE THREAD

**Issue by NowakAdmin** [kduma/L5-emSzmal-api#10]
Currently there are some missing code to handle token_value, I created a pull request with fix.

**Comment by kduma** [comment]
Yep. I've forgot about that property, but it was working.

I would find that anyway, while upgrading app for PHP 8.2 (Deprecation of dynamic properties), but you saved me a few WTF moments. 

Thanks 😄 

P. S. I haven't used "token_value", as for my bank it is not used.
